FROM ubuntu_base:latest

WORKDIR /usr/src/app

COPY submodules/AndScanner/requirements.txt ./
RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt

COPY submodules/AndScanner/. .

ENTRYPOINT [ "python3", "./scan.py" ]